# Generated by Django 4.1.3 on 2022-11-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_why1_post_why2_post_why3_post_why_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='why1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='why2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='why3',
        ),
    ]
