# Generated by Django 4.1.3 on 2022-11-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='maincourse',
        ),
    ]
