# Generated by Django 4.1.3 on 2022-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='maincourse',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.maincourse'),
        ),
    ]
