# Generated by Django 4.1.3 on 2022-11-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_hit_post_maincourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hit',
        ),
    ]
