# Generated by Django 4.1.3 on 2022-11-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_badge_remove_post_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_alt_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_tags',
        ),
    ]
