# Generated by Django 4.1.3 on 2022-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_image_alt_name_remove_post_meta_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='button_text',
            field=models.CharField(default='Enroll Now', max_length=20),
        ),
    ]
