# Generated by Django 4.1.3 on 2022-11-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='time_duration1',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='time_duration2',
        ),
    ]
