# Generated by Django 4.1.3 on 2022-11-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_timing_time_duration1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
