# Generated by Django 4.1.3 on 2022-11-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_order_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clients',
            new_name='passedstudents',
        ),
    ]
