# Generated by Django 4.1.3 on 2022-11-13 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_rename_clients_passedstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='enrolledstudents',
        ),
    ]
