# Generated by Django 4.1.3 on 2022-11-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_rename_customer_enrolledstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hit',
        ),
    ]
