# Generated by Django 4.1.3 on 2022-11-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_category_hit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offers',
        ),
    ]
