# Generated by Django 4.1.3 on 2022-11-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_delete_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='promocode',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
