# Generated by Django 4.1.3 on 2022-11-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_certificate_post_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tcforblog',
            name='blank_page',
        ),
        migrations.DeleteModel(
            name='blankpage',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='tcforblog',
        ),
    ]
