# Generated by Django 4.1.3 on 2022-11-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_delete_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
