# Generated by Django 4.1.3 on 2022-11-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
