# Generated by Django 4.1.3 on 2022-11-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_remove_payment_user_delete_orderplaced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='certificate',
        ),
    ]
