# Generated by Django 4.1.3 on 2022-11-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_remove_cart_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledstudents',
            name='City',
        ),
        migrations.RemoveField(
            model_name='enrolledstudents',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='enrolledstudents',
            name='Extension',
        ),
        migrations.RemoveField(
            model_name='enrolledstudents',
            name='State',
        ),
        migrations.RemoveField(
            model_name='enrolledstudents',
            name='Telephone',
        ),
        migrations.RemoveField(
            model_name='enrolledstudents',
            name='Zip_Code',
        ),
    ]
