# Generated by Django 4.1.3 on 2023-03-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
