# Generated by Django 4.1.3 on 2023-03-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
