# Generated by Django 4.1.3 on 2023-03-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutor',
        ),
    ]
