# Generated by Django 4.1.3 on 2023-03-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_delete_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
