# Generated by Django 4.1.3 on 2023-03-15 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.jobapplication')),
            ],
        ),
    ]
