# Generated by Django 4.1.3 on 2023-03-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_tutor_assigned_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='assigned_course',
        ),
        migrations.AddField(
            model_name='tutor',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_tutors', to='posts.post'),
        ),
    ]
