# Generated by Django 4.1.3 on 2023-03-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_studymaterial_liveclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slider_post',
        ),
    ]
