# Generated by Django 4.1.3 on 2023-03-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_remove_post_author_remove_post_disc_remove_post_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
    ]
