# Generated by Django 4.1.3 on 2023-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_post_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider_post',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
