# Generated by Django 4.1.3 on 2023-03-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_post_slider_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
