# Generated by Django 4.1.3 on 2023-03-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
