# Generated by Django 4.1.3 on 2023-05-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
    ]
